### ISSUE TITLE
ways to contribute | Formas de Contribuição e Estrutura de envio.

### ISSUE THREAD

**Issue by giovannism20** [mathvbarone/awesome-programming-languages#10]
Diante do crescimento do repositório, acho que deveríamos começar a estabeler estruturas para Contribuição, para envio de Pull Request e para abertura de Issue.

**Comment by giovannism20** [comment]
Não coloquei nada nos arquivos, de propósito, afinal, acho que deveríamos discutir isso de forma conjunta !

**Comment by mathvbarone** [comment]
Discussão transferida para a issue #13.
